CREATE TABLE Event(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day DATE NOT NULL,
  time_start TIME NOT NULL,
  time_end TIME NOT NULL,
  name TEXT NOT NULL,

  string TEXT NOT NULL,
  last_detection INTEGER NOT NULL
);

CREATE TABLE Location (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  capacity INTEGER
);

CREATE TABLE Year (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE Direction (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  FOREIGN KEY (year_id) REFERENCES Year(id) ON DELETE CASCADE
);

CREATE TABLE Subgroup (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  direction_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  FOREIGN KEY (direction_id) REFERENCES Direction(id) ON DELETE CASCADE
);

CREATE TABLE Teacher (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location_id INTEGER,
  FOREIGN KEY (location_id) REFERENCES Location(id)
);

CREATE TABLE EventLocation (
  event_id INTEGER,
  location_id INTEGER,
  PRIMARY KEY (event_id, location_id),
  FOREIGN KEY (event_id) REFERENCES Event(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES Location(id) ON DELETE CASCADE
);

CREATE TABLE EventTeacher (
  event_id INTEGER,
  teacher_id INTEGER,
  PRIMARY KEY (event_id, teacher_id),
  FOREIGN KEY (event_id) REFERENCES Event(id) ON DELETE CASCADE,
  FOREIGN KEY (teacher_id) REFERENCES Teacher(id) ON DELETE CASCADE
);

CREATE TABLE EventYear (
  event_id INTEGER,
  year_id INTEGER,
  PRIMARY KEY (event_id, year_id),
  FOREIGN KEY (event_id) REFERENCES Event(id) ON DELETE CASCADE,
  FOREIGN KEY (year_id) REFERENCES Year(id) ON DELETE CASCADE
);

CREATE TABLE EventDirection(
  event_id INTEGER,
  direction_id INTEGER,
  PRIMARY KEY (event_id, direction_id),
  FOREIGN KEY (event_id) REFERENCES Event(id) ON DELETE CASCADE,
  FOREIGN KEY (direction_id) REFERENCES Direction(id) ON DELETE CASCADE
);

CREATE TABLE EventSubgroup(
  event_id INTEGER,
  subgroup_id INTEGER,
  PRIMARY KEY (event_id, subgroup_id),
  FOREIGN KEY (event_id) REFERENCES Event(id) ON DELETE CASCADE,
  FOREIGN KEY (subgroup_id) REFERENCES Subgroup(id) ON DELETE CASCADE
);

CREATE INDEX ix_event_string ON Event (string);
