services:
  postgres-events:
    container_name: event-database
    image: postgres:17.2-alpine3.21
    environment:
      #POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./PostgresDB/init:/docker-entrypoint-initdb.d
      - ./PostgresDB/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      #      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./PGAdmin/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - internal-network
      
  auth-database-service:
    build:
      context: ./AuthDataBase
    container_name: auth-database
    volumes:
      - ./AuthDataBase/dataBase:/app/db
    environment:
      - DATABASE_PATH=/app/db/userDataBase.db
    networks:
      - internal-network

  access-control-service:
    build:
      context: ./AccessControlService
    container_name: access-control
    volumes:
      - ./AccessControlService/.env:/app/.env
    networks:
      - internal-network
    depends_on:
      - auth-database-service

  data-process-service:
    build:
      context: ./DataProcess
    container_name: data-process
    volumes:
      - ./DataProcess/.env:/app/.env
#    ports:
#      - "8005:8005"
    networks:
      - internal-network
    depends_on:
      - postgres-events

  mock-service:
    build:
      context: ./mockService
    container_name: mock
    volumes:
      - ./mockService/.env:/app/.env
    networks:
      - internal-network

  api-gateway-service:
    build:
      context: ./APIGateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./APIGateway/.env:/app/.env
    networks:
      - internal-network
    depends_on:
      - access-control-service
      - mock-service
      - data-process-service

volumes:
  data:
  pgadmin-data:

networks:
  internal-network:
    driver: bridge
