services:
  postgres-events:
    container_name: event-database
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_USER: ${POSTGRES_EVENT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_EVENT_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./PostgresDB/init:/docker-entrypoint-initdb.d
      - ./PostgresDB/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal-network

  postgres-users:
    container_name: user-database
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./HashDB/init:/docker-entrypoint-initdb.d
      - ./HashDB/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - internal-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_USER} -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./PGAdmin/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - internal-network

  access-control-service:
    build:
      context: ./AccessControlService
    container_name: access-control
    volumes:
      - ./AccessControlService/.env:/app/.env
    ports:
      - "8001:8001"
    networks:
      - internal-network
    depends_on:
      postgres-users:
        condition: service_healthy

  data-process-service:
    build:
      context: ./DataProcess
    container_name: data-process
    volumes:
      - ./DataProcess/.env:/app/.env
#    ports:
#      - "8005:8005"
    networks:
      - internal-network
    depends_on:
      - postgres-events

  mock-service:
    build:
      context: ./mockService
    container_name: mock
    volumes:
      - ./mockService/.env:/app/.env
    networks:
      - internal-network

  api-gateway-service:
    build:
      context: ./APIGateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./APIGateway/.env:/app/.env
    networks:
      - internal-network
    depends_on:
      - access-control-service
      - mock-service
      - data-process-service

networks:
  internal-network:
    driver: bridge
