services:
  postgres:
    container_name: postgres_container
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_DB: "eventdb"
      POSTGRES_USER: "student"
      POSTGRES_PASSWORD: "password-to-change"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

volumes:
  data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
